services:
  - type: web
    name: chatapplication
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install --prefix backend && npm install --prefix frontend --include=dev && npm run build --prefix frontend
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
