services:
  - type: web
    name: chatapplication
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install --prefix backend && cd frontend && npm ci && npm run build && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
