services:
  - type: web
    name: chatapplication
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: node backend/src/server.js
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
